Data explorer
sdsna/dashboards.sdgindex.org pull request #15
Opened 2021-05-26 15:30 UTC by Sakala85

You can take them from helpers/data and dataStore

2021-06-02 15:00 UTC, finnwoelm-sdsn requested changes
Hey @Sakala85, great work!! Good job figuring out Nivo! Seems really amazing what you can do with it!! 🤯

I think it's almost ready to merge — I just have a couple comments/ideas. What do you think?

2021-06-02 15:03 UTC, finnwoelm-sdsn commented on package.json
> +    "@nivo/line": "^0.70.1",
Do you also need `@nivo/core`? Cypress test is currently failing because it's missing @nivo/core, I think.

2021-06-02 15:46 UTC, Sakala85 commented on package.json
> +    "@nivo/line": "^0.70.1",
Oh yes in the last version on my stolen mac I downloaded it

2021-06-02 15:51 UTC, Sakala85 commented on pages/explorer/[[...params]].js
> +  for (let year = 2000; year <= 2020; year++) {
Done

2021-06-02 16:08 UTC, Sakala85 commented on drawers/ExplorerNavigationDrawer.js
> +});
Done

2021-06-02 16:08 UTC, Sakala85 commented on components/IndicatorPerformance.js
> -import { getTrend } from "helpers/observations";
Yes you're right Done

2021-06-02 16:32 UTC, finnwoelm-sdsn commented on components/ExplorerIndicatorSelector.js
> +  const goals = getGoals(dataStore);
It's good! But this will fail if `dataStore` is not loaded yet.

You could use the same approach as with `options`. Or you could add `if (!dataStore.isLoaded) return null;` (or `DrawerLoadingIndicator`, like we do in many drawers.

2021-06-02 16:33 UTC, finnwoelm-sdsn commented on components/ExplorerIndicatorSelector.js
> +                  onClick={() => router.push(explorerAssessmentUrl(option))}
This is actually exactly the same as

`<Button href={explorerAssessmentUrl(option}` />

but shorter and you don't need to add `useRouter`.

2021-06-03 08:43 UTC, Sakala85 commented on components/ExplorerIndicatorSelector.js
> +                  onClick={() => router.push(explorerAssessmentUrl(option))}
Ok perfect ahah

2021-06-03 08:52 UTC, Sakala85 commented on layouts/ExplorerLayout.js
> +      >
Not the same, the display is different

2021-06-03 09:36 UTC, Sakala85 commented on components/ExplorerIndicatorSelector.js
> +  const goals = getGoals(dataStore);
Yes you're right I fixed it before merge

2021-06-03 09:37 UTC, finnwoelm-sdsn commented on layouts/ExplorerLayout.js
> +      >
Oh, ok. But what's the difference? :) The code looks the same?

https://github.com/sdsna/dashboards.sdgindex.org/blob/main/layouts/FullScreenAppLayout.js

```jsx
import { Box, Hidden } from "@material-ui/core";
import AppLayout from "layouts/AppLayout";
import MobileMenuOpenerButton from "components/MobileMenuOpenerButton";

const FullScreenAppLayout = ({ mobileMenuLabel, ...props }) => (
  <Box
    position="fixed"
    width={1}
    height={1}
    display="flex"
    flexDirection="column"
  >
    <AppLayout overflow="hidden" fluid={true} footer={false} {...props} />
    {mobileMenuLabel ? (
      <Hidden implementation="css" smUp>
        <MobileMenuOpenerButton label={mobileMenuLabel} />
      </Hidden>
    ) : null}
  </Box>
);

export default FullScreenAppLayout;
```

2021-06-03 09:38 UTC, finnwoelm-sdsn commented on flags/setup.js
> -    console.log("OK");
Maybe I'm crazy, but I thought we undid this? 🤣

2021-06-03 09:40 UTC, finnwoelm-sdsn commented
Deploy & Cypress tests are failing because `npm run build && npm run export` fails.

It's because /explorer/[[...slug]].js is a dynamic page, so the export paths need to be defined in `next.config.js`. Can you take care of that? 😊

2021-06-03 10:54 UTC, finnwoelm-sdsn requested changes
Good work! The app builds now :)

There are two failing tests caused by change in `explorerAssessmentUrl` helper. Can you fix? 😊

2021-06-03 10:54 UTC, finnwoelm-sdsn commented on helpers/routing.js
> +export const explorerAssessmentUrl = (assessment) =>
This breaks any components currently using `explorerAssessmentUrl`, which is why we have two failing Cypress tests atm.

I suggest that we undo this one.

2021-06-03 10:54 UTC, finnwoelm-sdsn commented on components/ExplorerIndicatorSelector.js
> +                <Button href={explorerAssessmentUrl(option)}>
```suggestion
                <Button href={explorerAssessmentUrl({ assessment: option })}>
```

See above.

2021-06-03 13:32 UTC, Sakala85 commented on components/ExplorerIndicatorSelector.js
> +                <Button href={explorerAssessmentUrl(option)}>
Done

2021-06-03 13:32 UTC, Sakala85 commented on helpers/routing.js
> +export const explorerAssessmentUrl = (assessment) =>
Done

2021-06-03 14:44 UTC, finnwoelm-sdsn approved these changes
Ok! I'm merging this :)

2021-06-03 14:44 UTC, merged