Add country profiles slug page
sdsna/dashboards.sdgindex.org pull request #20
Opened 2021-05-28 12:39 UTC by DonTouzi

2021-05-28 14:06 UTC, finnwoelm-sdsn requested changes
This looks great, @DonTouzi!!

For `next.config.js`, can you export the profile pages just for countries? At the moment, you can visit region profiles & income profiles. But for now, we only want to have countries.

For example: https://deploy-preview-20--sdr-twenty-one.netlify.app/profiles/low-income-countries

2021-05-28 21:19 UTC, DonTouzi commented on next.config.js
> +    const { regions } = require("./public/data/regions.json");
@FinnWoelm, you are right :), done

2021-05-31 08:12 UTC, finnwoelm-sdsn commented
Hi @DonTouzi, thank you for the fix! Now, the Cypress test is failing — do you want to take a look and see if you can find the problem and solution?

(Let me know if you get stuck)

2021-05-31 08:22 UTC, DonTouzi commented
> Hi @DonTouzi, thank you for the fix! Now, the Cypress test is failing — do you want to take a look and see if you can find the problem and solution?
> 
> (Let me know if you get stuck)

Yes, i'll check now

2021-05-31 09:05 UTC, DonTouzi commented
Hi @FinnWoelm, it's fixed :), i think you can merge

2021-05-31 09:38 UTC, finnwoelm-sdsn approved these changes
Great job! Perfect! Merging now 👍

2021-05-31 09:39 UTC, merged