Add search bar to country profiles page
sdsna/dashboards.sdgindex.org pull request #25
Opened 2021-05-31 13:56 UTC by DonTouzi

2021-05-31 14:32 UTC, DonTouzi commented
@finnwoelm-sdsn, tell me what do you think, for now i will add some cypress tests :)

2021-05-31 14:57 UTC, finnwoelm-sdsn requested changes
This is really good!!! I added a lot of comments, but they are very small points. Let me know if you want to have a quick chat!

2021-05-31 14:57 UTC, finnwoelm-sdsn commented on pages/profiles.js
> +import SearchIcon from "@material-ui/icons/Search";
```suggestion
import { Search } from 'mdi-material-design';
```

We use mdi-material-design library: https://materialdesignicons.com/ (it has a lot more icons)

2021-05-31 14:57 UTC, finnwoelm-sdsn commented on pages/profiles.js
> +      .includes(filter.normalize("NFD").replace(/[\u0300-\u036f]/g, ""));
Let's do one Cypress test to check that searching for country with accent works: Côte d'Ivoire, for example

2021-05-31 14:57 UTC, finnwoelm-sdsn commented on pages/profiles.js
> +          {regions.map((region) => (
```suggestion
          {regions.filter(isVisible).map((region) => (
```

2021-05-31 14:57 UTC, finnwoelm-sdsn commented on pages/profiles.js
> +              }}
```suggestion
```

Better to do the `.filter` before the `.map`, so React has to render fewer components (= faster). Because we have a `key` on this component, React can quickly determine which elements to add/remove/update.

2021-05-31 14:57 UTC, finnwoelm-sdsn commented on pages/profiles.js
> +      <Box my={4} style={{ flexGrow: 1 }}>
```suggestion
      <Box my={4}>
```

Don't need flexGrow, I think

2021-05-31 14:57 UTC, finnwoelm-sdsn commented on pages/profiles.js
> +              style={{ width: "100%" }}
```suggestion
              fullWidth
```

2021-05-31 14:57 UTC, finnwoelm-sdsn commented on pages/profiles.js
> +              inputProps={{ min: 0 }} // the change is here
```suggestion
```

What is this for?

2021-05-31 14:57 UTC, finnwoelm-sdsn commented on pages/profiles.js
> +          <Grid item style={{ width: "100%" }}>
```suggestion
          <Grid item xs={12} sm={6} md={4} lg={3} >
```

Not sure if these are the right choices, but maybe you can try different ones and see?

It's a grid with 12 columns, so 12 = 100%. 6 = 50%. 3 = 25%. etc...

![image](https://user-images.githubusercontent.com/55237550/120210939-a527cd80-c230-11eb-8b84-5c1bfd5f0942.png)

Source: https://material-ui.com/customization/breakpoints/#breakpoints

2021-05-31 14:57 UTC, finnwoelm-sdsn commented on package.json
> +    "@material-ui/icons": "^4.11.2",
```suggestion
```

No need because we use mdi-material-design (see below)

2021-05-31 14:57 UTC, finnwoelm-sdsn commented on pages/profiles.js
> +              variant="outlined"
```suggestion
              variant="filled"
```

Can you actually try `filled`? I just reread the Google blog and it seems that filled is now the preferred option: https://medium.com/google-design/the-evolution-of-material-designs-text-fields-603688b3fe03

2021-05-31 21:05 UTC, DonTouzi commented on pages/profiles.js
> +import SearchIcon from "@material-ui/icons/Search";
Ok, it's always good to know :)

2021-05-31 21:08 UTC, DonTouzi commented on pages/profiles.js
> +      <Box my={4} style={{ flexGrow: 1 }}>
You are right

2021-05-31 21:18 UTC, DonTouzi commented on pages/profiles.js
> +              variant="outlined"
no problem ;)

2021-05-31 21:26 UTC, DonTouzi commented on pages/profiles.js
> +              }}
Wow, thank you for your review Finn, a learn a lot

2021-05-31 21:28 UTC, DonTouzi commented on pages/profiles.js
> +              inputProps={{ min: 0 }} // the change is here
i try to use it for client side validation, like maxlenght = {{12}}, but i will remove it

2021-05-31 21:31 UTC, DonTouzi commented on pages/profiles.js
> +      .includes(filter.normalize("NFD").replace(/[\u0300-\u036f]/g, ""));
Ok

2021-05-31 21:39 UTC, DonTouzi commented on pages/profiles.js
> +              variant="outlined"
I think that for a better design we should keep the outlined because, with filled, it does not look good

2021-06-01 09:50 UTC, finnwoelm-sdsn approved these changes
Perfect 👍

2021-06-01 09:52 UTC, DonTouzi commented
> Perfect +1

We can merge i think :100:

2021-06-01 09:52 UTC, merged